### PR TITLE
MVC

### PR DESCRIPTION
**Pull request by MiraWassem**
JavaScript: I implemented check and delete buttons functions related to MVC design pattern. 

Edited the names of the classes to better be related to their roles.

### CODE REVIEW

**Review by MohamedRageh96 — APPROVED** [review]
everything seems good to me

**Review by rawanramadanseddik — APPROVED** [review]
Incredible !!!!

**Review by omrmhd5 — APPROVED** [review]
Form.js file is useless please remove it, Overall Good Job.

**Review by ManarMahmoud17 — APPROVED** [review]
Everything looks good!
 Nice work!

**Review by Rubazy — APPROVED** [review]
good work

**Pull request merged**
