### PR TITLE
Nouran

### PR DESCRIPTION
**Pull request by nourannnnnnnnnnnn**
### **javascript:adding model view controller** 
**Model:**
todos Array: Contains a list of initial tasks with properties: id, title, completed, created_at, and updated_at.
addTodo Method: Adds a new task to the todos array and calls view.
getTodos Method: Returns the current list of tasks.
removeTodo Method: Removes a task from the todos array based on its id.
updateTodo Method: Toggles the completed status of a task and updates the view by calling view.handleselectors.

**View:**
init Method: Initializes the view by rendering all tasks and setting up event listeners.
renderTodos Method: Renders all tasks from the model.
renderTodo Method: Renders a single task and attaches event listeners for marking as completed and deleting.
setupEventListeners Method: Sets up the form submission event listener.
handleselectors Method: Toggles the completed class for tasks based on their completed status.

### CODE REVIEW

**Review by rawanramadanseddik — COMMENTED** [review]
Everything is good, "I think"

**Review by rawanramadanseddik — APPROVED** [review]
Everything is good, "I think"

**Review by youssefibrahim22 — CHANGES_REQUESTED** [review]
why there are two html pages

**Review by DaliaAmr — APPROVED** [review]
evertrhing is good

**Review by DinaAyman03 — APPROVED** [review]
The code is well written, good.

**Review by AhmedElgalaly — CHANGES_REQUESTED** [review]
## Request updates

add the event listener in the controller
remove "page.html" makes nonsense

<mark>preferable :</mark> change javascript file name from "index.js" to something else [Click Here](https://stackoverflow.com/questions/32408259/why-do-people-name-their-files-index-html) for reference

**Comment by rawanramadanseddik** [comment]
Amazing !

**Review by ManarMahmoud17 — COMMENTED** [review]
"Everything looks good! Nice work!"

**Pull request merged**
