### PR TITLE
last update

### PR DESCRIPTION
**Pull request by ManarMahmoud17**
using a model-view-controller (MVC) pattern to manage and interact with the application's data. Here's  how the functions (PATCH,POST,DELETE) connect with a backend database.

### CODE REVIEW

**Review by DaliaAmr — APPROVED** [review]
everything is good

**Review by rawanramadanseddik — CHANGES_REQUESTED** [review]
please remove all the "console.logs()" 's

**Review by rawanramadanseddik — CHANGES_REQUESTED** [review]
please remove all the "console.logs()" 's

**Review by MiraWassem — APPROVED** [review]

**Review by rawanramadanseddik — APPROVED** [review]
More than Perfectoooo

**Review by nourannnnnnnnnnnn — APPROVED** [review]
good work

**Pull request merged**
