### PR TITLE
updatednew

### PR DESCRIPTION
**Pull request by nourannnnnnnnnnnn**
I have added function 
**addToServer in the Model**
which trigger function add (adding new tasks)

**deleteToDo in the controller** 
which trigger deleting todos

**updateToServe in the controller:**
trigger function update responsible for toggling

### CODE REVIEW

**Review by DaliaAmr — APPROVED** [review]
Everything is well-structured and good

**Review by rawanramadanseddik — APPROVED** [review]
Almost everything is changed, but it is good

**Review by DinaAyman03 — APPROVED** [review]
The code is good however it is cleaner code to remove the console.log after debugging

**Review by ManarMahmoud17 — APPROVED** [review]
Perfectooo

**Pull request merged**
